### ISSUE TITLE
Add integration with amazon-s3

### ISSUE THREAD

**Issue by ad-pro** [dbohdan/tclssg#10]
At the moment there is a built-in functionality to upload website to by the ftp.

It would be really good to get possibility to release site on amazon clound (see jeykill for details)

**Comment by dbohdan** [comment]
You can now use the `deployCustomCommand` setting to set up deployment with any CLI deployment tool. If you set up S3 deployment with one of the tools mentioned or something else please post your configuration and I'll add it to the README.
