### ISSUE TITLE
Nicer code for opening a browser

### ISSUE THREAD

**Issue by andreas-kupries** [dbohdan/tclssg#28]
The package at
    https://github.com/ActiveState/stackato-cli/tree/master/lib/browse
is more full-fledged when it comes to opening a browser.

I intend to put this package into Tcllib
(See ticket https://core.tcl.tk/tcllib/tktview/9853e83aee1da01f1868bedd23d58698c5946678).
In the meantime it might make sense to have it directly in Tclssg.

**Comment by dbohdan** [comment]
Thanks for the suggestion! I wasn't very satisfied with the existing code for this purpose. I will investigate your library soon.

**Comment by dbohdan** [comment]
Update: the library works very nicely for me on Linux. I will include it in the next release, 1.0.0b.
