### ISSUE TITLE
A config (or page?) setting for a navbar logo

### ISSUE THREAD

**Issue by dbohdan** [dbohdan/tclssg#31]

**Comment by dbohdan** [comment]
See page setting `navbarBrand`.

**Comment by andreas-kupries** [comment]
Thank you. Verified that it works.

Also noticed that when I added text after the image the system shows them vertically stacked, instead of horizontally. Any idea how to overcome that ?

For clarity, the navbar was rendered as
```
    logo   item1 item2
    text
```
whereas I had expected
```
    logo text item1 item2 ...
```

**Comment by dbohdan** [comment]
I don't know the answer offhand but I would try to wrap both the image and
the text in a single <div> and apply the CSS class "pull-left" to it.
--
Sent from my mobile device.

**Comment by andreas-kupries** [comment]
Ok.

**Comment by andreas-kupries** [comment]
Yes, that worked, mostly. The vertical alignment was still off, until I reduced the logo to 20x20.
I will have get a better understanding of bootstrap here to see how a lrger logo can be made to work.

Also found
  <http://stackoverflow.com/questions/18474564/bootstrap-3-navbar-with-logo>
and am currently reading that.

**Comment by andreas-kupries** [comment]
Back to 30x30, and styling for positioning. Looks ok now.
Oh, with that I can use the regular logo and let the browser scale it down!
Good. Happy now.

**Comment by dbohdan** [comment]
Instructions on how to accomplish this may be good material for the wiki.

--
