### ISSUE TITLE
Templating Engines

### ISSUE THREAD

**Issue by andreas-kupries** [dbohdan/tclssg#35]
Are you aware of

    https://core.tcl.tk/tcllib/doc/trunk/embedded/www/tcllib/files/modules/textutil/expander.html
    http://www.wjduquette.com/expand/
    http://wiki.tcl.tk/2082

?

Could be a source of ideas even if it does not fit in what you are wanting to do with the engine in ssg.

**Comment by dbohdan** [comment]
Yep. Early versions of the program did use `textutil::expander` but I found it to not be the right fit for Tclssg because of how it worked with loops. See https://github.com/dbohdan/tclssg/commit/5f9cb2f7cf77877c7bf8a7277732f5676b398829.
