### ISSUE TITLE
Bad links in sitemap.xml when config variable "url" not ending in "/"

### ISSUE THREAD

**Issue by andreas-kupries** [dbohdan/tclssg#36]
The system mis-generates the links i nthe sitemap.xml when the website config variable "url" does not end in a "/".

I believe that this is something which can be easily checked for and fixed either when the variable is used, or when it read.

**Comment by andreas-kupries** [comment]
Verified, ssg now throws an error when the closing "/" is missing.

Seeing the validate-config in the commit reminds that I wanted to file an enhancement, a "check" command which simply check the website.conf. Not just what is in validate-config now, but also things like finding deprecated settings and telling the user how to fix them, i.e. tell the new name of the setting. Stuff like that.

**Comment by dbohdan** [comment]
A "check" command is a good idea. Warnings could be introduced in
validate-config to provide the functionality you describe. However, with
version 1.0 on (or 1.1 the latest) I intend to have Tclssg follow SemVer,
so hopefully setting deprecation will be less of an issue.

--
Sent from my mobile device.
