### ISSUE TITLE
Doc request/Example: Form handling.

### ISSUE THREAD

**Issue by andreas-kupries** [dbohdan/tclssg#38]
Looked at your contact page <http://danyilbohdan.com/contact.html>
and saw a form instead of a mail address.

Was wondering how that form was specified for SSG, and also how the CGI backend was integrated.

... Ok, looked at the HTML and I suspect that the contact.md page got a host of inline html instead of markdown. And it looks that you are using some external form hosting service for handling submissions, which then mails things to you.

Regardless, that would IMHO make a nice example.
And a nice advanced example when implementing the CGI script as well.

**Comment by dbohdan** [comment]
The contact form is a free form from http://allforms.mailjol.net/. When I switched my website to Tclssg with Bootstrap I took their autogenerated HTML code, removed the inline CSS (`style="..."`), added Bootstrap classes and that was it. The HTML is just passed through. In the end `contact.md` is literally just the following (except for my id; I've removed it to discourage its use for testing):
```
{
    title {Contact me}
}
<form name="<my_id>" id="<my_id>" action="http://free.allforms.mailjol.net/u/<my_id>.php" method="POST" role="form">
    <div>Fields marked by * are required.</div>
    <div class="form-group">
        <label for="message">Message&thinsp;*</label>
        <textarea id="message" class="form-control" name="Message:"   placeholder="Enter message"></textarea>
    </div>
    <div class="form-group">
        <label for="name">Name</label>
        <input id="name" type="text" class="form-control" placeholder="Your name" name="Name:">
    </div>
    <div class="form-group">
        <label for="email">Email&thinsp;*</label>
        <input id="email" type="email" class="form-control" placeholder="Your email address" name="Email:">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>
```
This can be added to the FAQ later along with the information on external comment services.

**Comment by andreas-kupries** [comment]
Agreed. Could also be its own wiki page.
