### ISSUE TITLE
Diskspace optimization: "file link" before "file copy" for static files

### ISSUE THREAD

**Issue by andreas-kupries** [dbohdan/tclssg#42]
Looked into "copy-files" in utils.tcl, which seems to be used for the copying the static files into the output, i.e. website.

It simply uses 'file copy'. For websites with a large amount of static files, or simply a few large ones it would IMHO sense to try "file link -hard ..." first, and copy only if that fails. That way the static files in the output do not take additional space on the disk, as they become just alias names of the files in the input.

The fallback to 'file copy' would then deal with platforms which do not support hardlinks, or a setup where the output is on a different disk than the input (hard links can only be within a disk/device, not between different disks/devices).

I am not sure if this should be put into the general 'copy-files', as it may be used not just for the static files, but other things as well. If so a variant procedure 'link-files' should be made, and then used just for the static files, and nowhere else, with other uses of 'copy-files' keeping their semantics.

**Comment by dbohdan** [comment]
I disagree with this proposal: it will create surprising behavior and violate the assumption that all other static site generators seem to make that the content in the output directory is disposable and you are free to mess with it. An example of messing with static content would be minifying CSS and JS and recompressing images lossily. Hard linking by default would mean that a user could unwittingly alter an important file if he forgets to override the default behavior when trying to create a disposable copy (I wouldn't trust myself never to do this). While file copying could be optimized (e.g., by making it event-based and/or only copying those files that have been modified) I think that this not the right way to do it.

I've also run a benchmark and on my hardware (a 2009 ThinkPad with an SSD) with the default project plus two 100 MiB and around 1500 of 5 to 50 KiB static files:
```
$ time ./ssg.tcl build t/i t/o
[...]
./ssg.tcl build t/i t/o  0.71s user 4.62s system 68% cpu 7.733 total
```
That is about as large as I expect the static files directory to get and the time is reasonable (if it takes three to five times as long on a mechanical HDD that's still acceptable). For more complex scenarios I'd probably advise the user to just keep the static files elsewhere and set up a script to run `rsync` on `deploy-custom`.

I think an angle worth examining instead later is having Tclssg run `rsync` automatically on calls to `copy-files` when `rsync` is installed. That kind of proc could actually be reused in many Tcl applications.

**Comment by andreas-kupries** [comment]
__Postprocessing__! I had not thought of this at all.
Thanks for catching this bad idea of mine.
I hereby retract it.

Having not seen anything in tclssg allowing the user to do post-processing from within the tool would you like me to file the issue for that feature ? It is something which could be kept entirely out of it.

**Comment by dbohdan** [comment]
>Postprocessing! I had not thought of this at all.
>Thanks for catching this bad idea of mine.
>I hereby retract it.

No problem. :-)

>Having not seen anything in tclssg allowing the user to do post-processing from within the tool would you like me to file the issue for that feature ? It is something which could be kept entirely out of it.

I am not quite sure: on one hand this seems like feature creep but on the other we already have `deploy-custom`, which is a similar piece of functionality. For my personal website I run Tclssg from a Makefile, so that's where I'd put the postprocessing bits if I needed them. I'm generally leaning towards the idea that Tclssg should be called from scripts rather than the other way around. (The target audience for SSGs in general is fairly tech-savvy, so should not be an issue from the user-friendliness perspective.)

**Comment by andreas-kupries** [comment]
Ok.
