### ISSUE TITLE
Weirdness with pagePrelude

### ISSUE THREAD

**Issue by andreas-kupries** [dbohdan/tclssg#43]
Using <%! img-local .... %> in a page.

When the img.tcl is loaded in the page, via <% interp-source img.tcl %> all is fine, i.e. the image is in the page. If the command to source img.tcl is in the pagePrelude the image reference is rendered as a markdown __code block__ instead ... 

Aha, found the issue!

I wrote the prelude like a Tcl block, nicely indented in the website.conf.
So it ended in a new line of just 4 spaces. i.e.
```
        pagePrelude {
          <%! interp-source ... %>
        }
```

When it got assembled with the actual page these 4 spaces indented the first line of the page, which had the logo reference. Markdown then saw the indented line and said, ok, this is code, and rendered it as such.

When I rewrote the prelude to
```
        pagePrelude {<% interp-source ... %>}
```

i.e. eliminated the trailing spaces the render was ok again.

I believe that the general fix would/should be to trim trailing spaces from the prelude, and separate it from the regular content by at least a single empty line.

**Comment by andreas-kupries** [comment]
Unable to verify.

My fork is uptodate with a9d269c (actually one past that), and has no local changes.
Changing the prelude back to be without trailing spaces and it is ok again.
I will have a look and submit a pull request after I figure this out.

Together with an issue on another page where I see my macro code generating two tables, yet only the first appears in the output I might actually have a larger pull request implementing a dump feature where ssg dumps all stages of processing a file into a temp dir for analysis, i.e. input, past macro processing, past markdown, setup/past the templating stages, etc.

**Comment by andreas-kupries** [comment]
I am able to verify the change of variables to settings however, and that works, after me updating my shortcuts, so that is good.

**Comment by andreas-kupries** [comment]
Good prelude

    ==> website/tmp/logo_d2Vic2l0ZS9pbnB1dC9wYWdlcy9sb2dvLm1k.content-0-raw <==
    <%!iref logo%>

    ==> website/tmp/logo_d2Vic2l0ZS9pbnB1dC9wYWdlcy9sb2dvLm1k.content-1-2expand <==
    <% interp-source shortcuts.tcl ; interp-source img.tcl %><%!iref logo%>

    ==> website/tmp/logo_d2Vic2l0ZS9pbnB1dC9wYWdlcy9sb2dvLm1k.content-2-markdown <==
    <img src="./images/logo.big.jpeg" class="img-responsive" alt="AC">

"Bad" prelude

    ==> website/tmp/logo_d2Vic2l0ZS9pbnB1dC9wYWdlcy9sb2dvLm1k.content-0-raw <==
    <%!iref logo%>

    ==> website/tmp/logo_d2Vic2l0ZS9pbnB1dC9wYWdlcy9sb2dvLm1k.content-1-2expand <==
            <% interp-source shortcuts.tcl ; interp-source img.tcl %>
        <%!iref logo%>

    ==> website/tmp/logo_d2Vic2l0ZS9pbnB1dC9wYWdlcy9sb2dvLm1k.content-2-markdown <==

        <img src="./images/logo.big.jpeg" class="img-responsive" alt="AC">

Input (0-raw) is the same. With prelude (1-2expand) added the iref gets indented from the prelude content. This indentation is left after expansion (2-markdown), and markdown renders it as code block.

My fix is to put a newline between prelude and content.
That works.
Dropping the whole trim-indentation works as well, as long as there is a newline between prelude and actual content.

Note: [join [list $a $b $c] ""] is the same as  $a$b$c, just not as readable IMVHO.

**Comment by dbohdan** [comment]
>My fork is uptodate with a9d269c (actually one past that), and has no local changes.
Changing the prelude back to be without trailing spaces and it is ok again.
I will have a look and submit a pull request after I figure this out.

I should have been more clear about what this update does. It does **not** remove trailing spaces from the prelude, rather, it just unindents it by as many spaces as possible and removes those lines at the beginning and the end of the text that turn out empty as a result. This means it will help with

        pagePrelude {
          <% interp-source img.tcl %>
        }

but won't with

        pagePrelude {<% interp-source img.tcl %>      }

The reason for this approach was to allow the user to use the prelude that would modify the first line of the content if that's what he wants. On second thought, this is too arcane to matter.

I will keep the `trim-indentation` and insert a newline after the prelude. The reason `trim-indentation` is there is so that

```
pageSettings {
    pagePrelude {
        Content:

        <%! some-command %>
    }
}
```

wouldn't produce fixed-width content but

```
pageSettings {
    pagePrelude {
        Content:

            <%! some-command %>
    }
}
```

would.

**Comment by dbohdan** [comment]
>Note: [join [list $a $b $c] ""] is the same as $a$b$c, just not as readable IMVHO.

I find
```
[join [list [long-command-1 ...]\
    [long-command-2 ...]] ""]
```
more readable than
```
"[long-command-1 \
    ...][long-command-2 ...]"
```

 when line wrapped and it is harder accidentally introduce a space this way. Note that I do not use `string cat` for 8.5 compatibility (which is a goal for Tclssg).

**Comment by andreas-kupries** [comment]
Heh. My preference in such a case then becomes to use helper variables to get the strings and then assemble the final form from these variables. Partially a master of taste.

**Comment by dbohdan** [comment]
>My preference in such a case then becomes to use helper variables to get the strings and then assemble the final form from these variables.

That's probably a better solution in most cases. The only downside is if you use it in a proc like `compile-website` where there are lots of local variables that you might accidentally affect. (Though I suppose you could make those variables constants after they are first set by tracing attempts to write to them and raising an error.)

**Comment by andreas-kupries** [comment]
Another possibility is to give either the proc-local or namespace variables some sort of prefix in their name which makes them quickly identifiable (In OO work I like to name instance variables as "my..." to identify them).
